name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and push to Docker 
      uses: docker/build-push-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{github.repository}}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{github.sha}}
      
